<?php

use Illuminate\Database\Seeder;
use App\Food;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Food::class, 100)->create();
        Food::query()->delete();
        Food::insert($this->data());
    }

    public function data()
    {
        return [
            [ 'id' => 1, 'descrip' => 'ACHITA, KIWICHA O ACHIS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 2, 'descrip' => 'ARROZ PILADO O PULIDO COCIDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 3, 'descrip' => 'ARROZ BLANCO GOURMET' , 'ingredient_type_id' => 1 ],
            [ 'id' => 4, 'descrip' => 'ARROZ CON CÁSCARA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 5, 'descrip' => 'AVENA ENVASADA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 6, 'descrip' => 'AVENA, HOJUELA COCIDA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 7, 'descrip' => 'AVENA, HOJUELA CRUDA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 8, 'descrip' => 'CAÑIHUA AMARILLA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 9, 'descrip' => 'CAÑIHUA GRIS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 10, 'descrip' => 'CAÑIHUA, HOJUELAS DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 11, 'descrip' => 'CAÑIHUA PARDA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 12, 'descrip' => 'CEBADA CON CÁSCARA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 13, 'descrip' => 'CEBADA, LLUNKA DE (MORÓN AMERICANO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 14, 'descrip' => 'CEBADA, MASHKA O MACHICA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 15, 'descrip' => 'CEBADA PARA MOTE, PELADA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 16, 'descrip' => 'CEBADA TOSTADA, HARINA INTEGRAL' , 'ingredient_type_id' => 1 ],
            [ 'id' => 17, 'descrip' => 'CEBADA PERLADA O RESBALADA COCIDA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 18, 'descrip' => 'CEBADA PERLADA O RESBALADA CRUDA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 19, 'descrip' => 'CEBADA TOSTADA Y MOLIDA (CHAQUEPA)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 20, 'descrip' => 'CHANCAY (BIZCOCHO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 21, 'descrip' => 'FIDEO CRUDO FORTIFICADO CON HIERRO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 22, 'descrip' => 'FIDEO TALLARÍN CRUDO FORTIFICADO CON HIERRO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 23, 'descrip' => 'FIDEO TALLARÍN SANCOCHADO FORTITICADO CON HIERRO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 24, 'descrip' => 'GALLETA DE SODA (SALADA)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 25, 'descrip' => 'GALLETA DE VAINILLA (DULCE)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 26, 'descrip' => 'MAIZ ALAZAN' , 'ingredient_type_id' => 1 ],
            [ 'id' => 27, 'descrip' => 'MAIZ ALAZAN, JORA FRESCA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 28, 'descrip' => 'MAIZ ALAZAN, JORA SECA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 29, 'descrip' => 'MAIZ AMARILLO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 30, 'descrip' => 'MAIZ, BLANCO CRUDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 31, 'descrip' => 'MAÍZ, BLANCO TOSTADO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 32, 'descrip' => 'MAIZ, CANCHA TOSTADA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 33, 'descrip' => 'MAIZ, CHOCHOCA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 34, 'descrip' => 'MAIZ, GRANO FRESCO (CHOCLO DESGRANADO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 35, 'descrip' => 'MAIZ, GERMINADO SECO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 36, 'descrip' => 'MAIZ, HARINA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 37, 'descrip' => 'MAICENA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 38, 'descrip' => 'MAIZ, MORADO P.C.' , 'ingredient_type_id' => 1 ],
            [ 'id' => 39, 'descrip' => 'MAIZ, MOTE DE (SANCOCHADO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 40, 'descrip' => 'MAIZ, PACHUCO DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 41, 'descrip' => 'MAIZ, PARA MOTE PELADO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 42, 'descrip' => 'MAIZ, PARA MOTE SIN PELAR' , 'ingredient_type_id' => 1 ],
            [ 'id' => 43, 'descrip' => 'POLENTA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 44, 'descrip' => 'MAIZ, TOCOSH CRUDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 45, 'descrip' => 'PAN DE CEBADA (SERRANO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 46, 'descrip' => 'PAN DE LABRANZA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 47, 'descrip' => 'PAN DE MOLDE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 48, 'descrip' => 'PAN FRANCÉS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 49, 'descrip' => 'PAN FRANCÉS FORTIFICADO CON HIERRO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 50, 'descrip' => 'QUINUA, AFRECHO DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 51, 'descrip' => 'QUINUA BLANCA (JUNÍN)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 52, 'descrip' => 'QUINUA BLANCA (PUNO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 53, 'descrip' => 'QUINUA COCIDA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 54, 'descrip' => 'QUINUA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 55, 'descrip' => 'QUINUA DULCE, BLANCA (JUNÍN)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 56, 'descrip' => 'QUINUA DULCE, BLANCA (PUNO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 57, 'descrip' => 'QUINUA DULCE, ROSADA (JUNÍN)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 58, 'descrip' => 'QUINUA, HARINA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 59, 'descrip' => 'QUINUA, HOJUELAS DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 60, 'descrip' => 'QUINUA ROSADA (PUNO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 61, 'descrip' => 'QUINUA, SEMOLA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 62, 'descrip' => 'SORGO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 63, 'descrip' => 'TRIGO, HARINA FORTIFICADA CON HIERRO DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 64, 'descrip' => 'TRIGO, LLUNKA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 65, 'descrip' => 'TRIGO, HARINA TOSTADA DE (MACHICA)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 66, 'descrip' => 'TRIGO, MOTE DE (SANCOCHADO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 67, 'descrip' => 'TRIGO PARA MOTE PELADO COCIDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 68, 'descrip' => 'TRIGO PARA MOTE PELADO CRUDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 69, 'descrip' => 'TRIGO, PELADO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 70, 'descrip' => 'TRIGO RESBALADO COCIDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 71, 'descrip' => 'TRIGO RESBALADO CRUDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 72, 'descrip' => 'TRIGO, SEMOLA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 73, 'descrip' => 'TRIGO PARTIDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 74, 'descrip' => 'FIDEO CORBATITA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 75, 'descrip' => 'FREJOL PANAMITO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 76, 'descrip' => 'FIDEOS CHINOS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 77, 'descrip' => 'PAN RALLADO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 78, 'descrip' => 'HARINA DE  CHUÑO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 79, 'descrip' => 'PAN DE YEMA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 80, 'descrip' => 'ARROCILLO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 81, 'descrip' => 'FIDEO ARITOS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 82, 'descrip' => 'FIDEO CABELLO DE ANGEL' , 'ingredient_type_id' => 1 ],
            [ 'id' => 83, 'descrip' => 'FIDEO CANUTO GRANDE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 84, 'descrip' => 'FIDEO CANUTO CHICO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 85, 'descrip' => 'FIDEO CODITOS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 86, 'descrip' => 'FIDEO LETRITAS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 87, 'descrip' => 'FIDEO PLUMITA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 88, 'descrip' => 'FIDEO MUNICIÓN' , 'ingredient_type_id' => 1 ],
            [ 'id' => 89, 'descrip' => 'FIDEO PEPITA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 90, 'descrip' => 'FIDEO SPAGUETTI MARCO POLO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 91, 'descrip' => 'FIDEO SPAGUETTI DON VICTORIO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 92, 'descrip' => 'FIDEO SPAGUETTI MOLITALIA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 93, 'descrip' => 'FIDEO TALLARÍN GRUESO ALIANZA CON HUEVO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 94, 'descrip' => 'FIDEO TALLARÍN GRUESO DON VICTORIO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 95, 'descrip' => 'FIDEO TALLARÍN GRUESO ESPIGA DE ORO ' , 'ingredient_type_id' => 1 ],
            [ 'id' => 96, 'descrip' => 'FIDEO TORNILLO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 97, 'descrip' => 'HARINA 7 SEMILLAS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 98, 'descrip' => 'HARINA DE ARVERJA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 99, 'descrip' => 'HARINA DE HABAS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 100, 'descrip' => 'HARINA DE KIWICHA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 101, 'descrip' => 'HARINA DE TAMAL' , 'ingredient_type_id' => 1 ],
            [ 'id' => 102, 'descrip' => 'HARINA DE SOYA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 103, 'descrip' => 'TRIGO, HARINA PREPARADA DE' , 'ingredient_type_id' => 1 ],
            [ 'id' => 104, 'descrip' => 'PONCHE DE HABAS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 105, 'descrip' => 'MORÓN PARTIDO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 106, 'descrip' => 'LINAZA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 107, 'descrip' => 'TARWI O CHOCHO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 108, 'descrip' => 'TRIGO AMARILLO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 109, 'descrip' => 'FREJOL BAYO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 110, 'descrip' => 'FREJOL CABALLERO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 111, 'descrip' => 'FREJOL CASTILLA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 112, 'descrip' => 'FREJOL NEGRO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 113, 'descrip' => 'FREJOL ROJO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 114, 'descrip' => 'FREJOL CAMANEJO' , 'ingredient_type_id' => 1 ],
            [ 'id' => 115, 'descrip' => 'FREJOL CÁPSULA' , 'ingredient_type_id' => 1 ],
            [ 'id' => 116, 'descrip' => 'HABAS SECAS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 117, 'descrip' => 'LENTEJA NORMAL' , 'ingredient_type_id' => 1 ],
            [ 'id' => 118, 'descrip' => 'PALLAR BEBÉ' , 'ingredient_type_id' => 1 ],
            [ 'id' => 119, 'descrip' => 'MAIZ, GRANO FRESCO (CHOCLO ENTERO)' , 'ingredient_type_id' => 1 ],
            [ 'id' => 120, 'descrip' => 'HARINA DE SIETE SEMILLAS' , 'ingredient_type_id' => 1 ],
            [ 'id' => 121, 'descrip' => 'ACELGA, HOJAS C/TALLO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 122, 'descrip' => 'ACELGA, TALLOS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 123, 'descrip' => 'AJÍ AMARILLO FRESCO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 124, 'descrip' => 'AJÍ AMARILLO MOLIDO FRESCO SIN SAL' , 'ingredient_type_id' => 2 ],
            [ 'id' => 125, 'descrip' => 'AJÍ AMARILLO SECO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 126, 'descrip' => 'AJÍ PANCA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 127, 'descrip' => 'AJÍ COLORADO NO PICANTE (MOLIDO CON SAL)' , 'ingredient_type_id' => 2 ],
            [ 'id' => 128, 'descrip' => 'AJÍ COLORADO MOLIDO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 129, 'descrip' => 'AJÍ DE MESA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 130, 'descrip' => 'AJÍ DE VAINA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 131, 'descrip' => 'AJÍ DULCE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 132, 'descrip' => 'AJÍ VERDE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 133, 'descrip' => 'AJO SIN CÁSCARA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 134, 'descrip' => 'ALBAHACA SIN TALLO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 135, 'descrip' => 'ALCACHOFA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 136, 'descrip' => 'ALFALFA BROTES TIERNOS' , 'ingredient_type_id' => 2 ],
            [ 'id' => 137, 'descrip' => 'APIO SIN HOJAS' , 'ingredient_type_id' => 2 ],
            [ 'id' => 138, 'descrip' => 'BERENJENA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 139, 'descrip' => 'BERENJENA COSTEÑA O TOMATE DE ÁRBOL' , 'ingredient_type_id' => 2 ],
            [ 'id' => 140, 'descrip' => 'BERRO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 141, 'descrip' => 'BROCOLI P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 142, 'descrip' => 'CAIGUA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 143, 'descrip' => 'CAIGUA DEL PAÍS P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 144, 'descrip' => 'CALABAZA CHINA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 145, 'descrip' => 'CALABAZA SERRANA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 146, 'descrip' => 'CEBOLLA BLANCA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 147, 'descrip' => 'CEBOLLA CHILENA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 148, 'descrip' => 'CEBOLLITA CHINA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 149, 'descrip' => 'CEBOLLA DE CABEZA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 150, 'descrip' => 'CEBOLLA DE COLA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 151, 'descrip' => 'COL BLANCA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 152, 'descrip' => 'COL CRESPA O REPOLLO, SIN COGOLLO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 153, 'descrip' => 'COL CHINA SIN TALLO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 154, 'descrip' => 'COL DE "BRUSELAS" P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 155, 'descrip' => 'COL, HOJAS DE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 156, 'descrip' => 'COL NEGRA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 157, 'descrip' => 'COL SILVESTRE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 158, 'descrip' => 'COLIFLOR P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 159, 'descrip' => 'CULANTRO SIN TALLO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 160, 'descrip' => 'CHICLAYO, CALABAZA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 161, 'descrip' => 'CHONTA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 162, 'descrip' => 'ESCAROLA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 163, 'descrip' => 'ESPARRAGOS P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 164, 'descrip' => 'ESPINACA  P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 165, 'descrip' => 'ESPINACA NEGRA SIN TRONCO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 166, 'descrip' => 'FRIJOLITO CHINO GERMINADO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 167, 'descrip' => 'HIERBABUENA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 168, 'descrip' => 'HUACATAY P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 169, 'descrip' => 'JANCHOY, HOJAS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 170, 'descrip' => 'JETKA. HOJAS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 171, 'descrip' => 'KAILÁN. HOJAS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 172, 'descrip' => 'KAILÁN. TALLOS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 173, 'descrip' => 'LECHUGA AMERICANA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 174, 'descrip' => 'LECHUGA ROMANA LARGA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 175, 'descrip' => 'LECHUGA ORGÁNICA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 176, 'descrip' => 'MANCHAY P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 177, 'descrip' => 'MASTUERZO, HOJAS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 178, 'descrip' => 'MOSTAZA, HOJAS DE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 179, 'descrip' => 'MUÑA, SECA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 180, 'descrip' => 'NABO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 181, 'descrip' => 'NABO, HOJAS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 182, 'descrip' => 'ORÉGANO FRESCO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 183, 'descrip' => 'PACCHOY, HOJAS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 184, 'descrip' => 'PACCHOY, TALLOS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 185, 'descrip' => 'PAICO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 186, 'descrip' => 'PAJURO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 187, 'descrip' => 'PEPINILLO SIN CÁSCARA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 188, 'descrip' => 'PEREJIL SIN TALLO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 189, 'descrip' => 'PIMIENTO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 190, 'descrip' => 'PIRCA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 191, 'descrip' => 'PORO SIN HOJAS' , 'ingredient_type_id' => 2 ],
            [ 'id' => 192, 'descrip' => 'QUINUA, HOJAS DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 193, 'descrip' => 'RABANITOS P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 194, 'descrip' => 'RABICOL P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 195, 'descrip' => 'RADICHETA O ACHICORIA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 196, 'descrip' => 'ROCOTO FRESCO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 197, 'descrip' => 'RUDA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 198, 'descrip' => 'SIUCA CULANTRO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 199, 'descrip' => 'TOMATE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 200, 'descrip' => 'TOMATE ITALIANO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 201, 'descrip' => 'TOMATE, CON CARNE SALSA DE ' , 'ingredient_type_id' => 2 ],
            [ 'id' => 202, 'descrip' => 'TOMATE, SALSA DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 203, 'descrip' => 'TOMATE, SALSA CONCENTRADA DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 204, 'descrip' => 'VAINITAS P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 205, 'descrip' => 'ZANAHORIA AMARILLA SIN CÁSCARA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 206, 'descrip' => 'ZANAHORIA, HARINA DE' , 'ingredient_type_id' => 2 ],
            [ 'id' => 207, 'descrip' => 'ZAPALLO ITALIANO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 208, 'descrip' => 'ZAPALLO LOCHE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 209, 'descrip' => 'ZAPALLO MACRE P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 210, 'descrip' => 'ARVERJA FRESCA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 211, 'descrip' => 'ARVEJAS VERDES FRESCAS' , 'ingredient_type_id' => 2 ],
            [ 'id' => 212, 'descrip' => 'HABAS FRESCAS' , 'ingredient_type_id' => 2 ],
            [ 'id' => 213, 'descrip' => 'CEBOLLA  ROJA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 214, 'descrip' => 'AJÍ LIMO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 215, 'descrip' => 'ANÍS FRESCO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 216, 'descrip' => 'BOLDO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 217, 'descrip' => 'CHINCHO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 218, 'descrip' => 'COLANTAO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 219, 'descrip' => 'ENELDO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 220, 'descrip' => 'ESTRAGÓN' , 'ingredient_type_id' => 2 ],
            [ 'id' => 221, 'descrip' => 'FRIJOL VERDE FRESCO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 222, 'descrip' => 'FREJOL VERDE PELADO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 223, 'descrip' => 'HIERBA LUISA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 224, 'descrip' => 'HINOJO P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 225, 'descrip' => 'LECHUGA MORADA' , 'ingredient_type_id' => 2 ],
            [ 'id' => 226, 'descrip' => 'LECHUGA CRIOLLA O DE SEDA P.C.' , 'ingredient_type_id' => 2 ],
            [ 'id' => 227, 'descrip' => 'MANZANILLA ' , 'ingredient_type_id' => 2 ],
            [ 'id' => 228, 'descrip' => 'TORONJIL' , 'ingredient_type_id' => 2 ],
            [ 'id' => 229, 'descrip' => 'ROMERO' , 'ingredient_type_id' => 2 ],
            [ 'id' => 230, 'descrip' => 'ABRIDORES P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 231, 'descrip' => 'ACEITUNA DE BOTIJA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 232, 'descrip' => 'ACEITUNAS NEGRAS PREPARADAS P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 233, 'descrip' => 'AIRAMPO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 234, 'descrip' => 'AGUAJE P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 235, 'descrip' => 'ANONA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 236, 'descrip' => 'MELOCOTÓN-DURAZNO CHICO (80 - 100 gr)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 237, 'descrip' => 'CAIMITO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 238, 'descrip' => 'CAMU-CAMU P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 239, 'descrip' => 'CAPULÍ P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 240, 'descrip' => 'CHAMBIRO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 241, 'descrip' => 'CHIRIMOYA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 242, 'descrip' => 'CIRUELA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 243, 'descrip' => 'COCO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 244, 'descrip' => 'COCO, AGUA DE' , 'ingredient_type_id' => 3 ],
            [ 'id' => 245, 'descrip' => 'COCONA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 246, 'descrip' => 'DÁTILES P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 247, 'descrip' => 'FRESA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 248, 'descrip' => 'GRANADA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 249, 'descrip' => 'GRANADILLA P.C. x 180 g.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 250, 'descrip' => 'GRANADILLA, JUGO ENLATADO DE' , 'ingredient_type_id' => 3 ],
            [ 'id' => 251, 'descrip' => 'GUANÁBANA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 252, 'descrip' => 'GUAYABA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 253, 'descrip' => 'GUAYABA AMARILLA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 254, 'descrip' => 'GUAYABA ROSADA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 255, 'descrip' => 'GUAYABA VERDE P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 256, 'descrip' => 'HIGO NEGRO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 257, 'descrip' => 'HIGO SECO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 258, 'descrip' => 'HUITO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 259, 'descrip' => 'HUMARÍ P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 260, 'descrip' => 'KAKI P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 261, 'descrip' => 'KUMUVI P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 262, 'descrip' => 'LIMA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 263, 'descrip' => 'LIMÓN P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 264, 'descrip' => 'LÚCUMA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 265, 'descrip' => 'LÚCUMA, HARINA DE' , 'ingredient_type_id' => 3 ],
            [ 'id' => 266, 'descrip' => 'MACAMBO, PULPA Y SEMILLA' , 'ingredient_type_id' => 3 ],
            [ 'id' => 267, 'descrip' => 'MACAMBO, PULPA DE' , 'ingredient_type_id' => 3 ],
            [ 'id' => 268, 'descrip' => 'MAMEY MADURO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 269, 'descrip' => 'MANDARINA P.C. x 180 g.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 270, 'descrip' => 'MANGO JUGO (120-130 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 271, 'descrip' => 'MANZANA DELICIA (PURÉ) 100-110 g.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 272, 'descrip' => 'MARACUYÁ P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 273, 'descrip' => 'MARAÑÓN P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 274, 'descrip' => 'MELÓN P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 275, 'descrip' => 'MELÓN ENANO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 276, 'descrip' => 'MEMBRILLO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 277, 'descrip' => 'NARANJA DE MESA  P.C. (220 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 278, 'descrip' => 'NARANJA DE JUGO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 279, 'descrip' => 'NARANJA DE GUAYAQUIL P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 280, 'descrip' => 'NARANJA DE HUANDO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 281, 'descrip' => 'NÍSPERO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 282, 'descrip' => 'NUZIVE P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 283, 'descrip' => 'PACAE  Ó GUABA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 284, 'descrip' => 'PALTA P.C. (DESAYUNO)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 285, 'descrip' => 'PAN DE ÁRBOL CON SEMILLA' , 'ingredient_type_id' => 3 ],
            [ 'id' => 286, 'descrip' => 'PAN DE ÁRBOL SIN SEMILLA' , 'ingredient_type_id' => 3 ],
            [ 'id' => 287, 'descrip' => 'PAN-MEO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 288, 'descrip' => 'PAPAYA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 289, 'descrip' => 'PASAS SIN PEPAS' , 'ingredient_type_id' => 3 ],
            [ 'id' => 290, 'descrip' => 'PEPINO DULCE P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 291, 'descrip' => 'PERA CHILENA P.C. (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 292, 'descrip' => 'PERA (puré) P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 293, 'descrip' => 'PERA NACIONAL P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 294, 'descrip' => 'PERA PERILLA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 295, 'descrip' => 'PEROS P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 296, 'descrip' => 'PIJUAYO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 297, 'descrip' => 'PIJUAYO SANCOCHADO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 298, 'descrip' => 'PIÑA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 299, 'descrip' => 'PLÁTANO DE ISLA P.C. - LUNES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 300, 'descrip' => 'PLÁTANO DE SEDA P.C- LUNES.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 301, 'descrip' => 'PLÁTANO PALILLO P.C. (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 302, 'descrip' => 'PLÁTANO MANZANO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 303, 'descrip' => 'PLÁTANO, HARINA DE' , 'ingredient_type_id' => 3 ],
            [ 'id' => 304, 'descrip' => 'PLÁTANO BELLACO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 305, 'descrip' => 'PLÁTANO MORADO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 306, 'descrip' => 'PLÁTANO SECO (OREJÓN)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 307, 'descrip' => 'PLÁTANO VERDE P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 308, 'descrip' => 'PLÁTANO VERDE ASADO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 309, 'descrip' => 'PLÁTANO VERDE SANCOCHADO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 310, 'descrip' => 'POMAROSA' , 'ingredient_type_id' => 3 ],
            [ 'id' => 311, 'descrip' => 'PURUNKARI P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 312, 'descrip' => 'SANDIA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 313, 'descrip' => 'SHIWAWACO (SEMILLA)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 314, 'descrip' => 'TAMARINDO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 315, 'descrip' => 'MANGO CIRUELO (TAPERIBÁ) P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 316, 'descrip' => 'TORONJA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 317, 'descrip' => 'TUMBO COSTEÑO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 318, 'descrip' => 'TUMBO SERRANO P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 319, 'descrip' => 'TUNA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 320, 'descrip' => 'TUNA COLORADA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 321, 'descrip' => 'UNGURAUY P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 322, 'descrip' => 'UVA BLANCA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 323, 'descrip' => 'UVA BORGOÑA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 324, 'descrip' => 'UVA ITALIA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 325, 'descrip' => 'UVA NEGRA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 326, 'descrip' => 'UVA QUEBRANTA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 327, 'descrip' => 'UVILLA P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 328, 'descrip' => 'ZAPOTE P.C.' , 'ingredient_type_id' => 3 ],
            [ 'id' => 329, 'descrip' => 'DURAZNO (160 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 330, 'descrip' => 'DURAZNO (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 331, 'descrip' => 'MANGO (220 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 332, 'descrip' => 'MANZANA DELICIA (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 333, 'descrip' => 'MANZANA FUJI (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 334, 'descrip' => 'MANZANA ISRAEL (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 335, 'descrip' => 'MANZANA ROYAL (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 336, 'descrip' => 'MANZANA VERDE (180 g.)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 337, 'descrip' => 'MANZANA DE AGUA  ' , 'ingredient_type_id' => 3 ],
            [ 'id' => 338, 'descrip' => 'PALTA (palta rellena)' , 'ingredient_type_id' => 3 ],
            [ 'id' => 339, 'descrip' => 'PALTA FUERTE - LUNES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 340, 'descrip' => 'PALTA FUERTE - MARTES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 341, 'descrip' => 'PALTA FUERTE - MIERCOLES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 342, 'descrip' => 'PALTA FUERTE - JUEVES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 343, 'descrip' => 'PALTA FUERTE - VIERNES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 344, 'descrip' => 'PALTA FUERTE - SABADO ' , 'ingredient_type_id' => 3 ],
            [ 'id' => 345, 'descrip' => 'PALTA FUERTE - DOMINGO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 346, 'descrip' => 'PLÁTANO DE ISLA P.C.- MARTES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 347, 'descrip' => 'PLÁTANO DE ISLA P.C.- MIÉRCOLES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 348, 'descrip' => 'PLÁTANO DE ISLA P.C.- JUEVES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 349, 'descrip' => 'PLÁTANO DE ISLA P.C.- VIERNES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 350, 'descrip' => 'PLÁTANO DE ISLA P.C.- SÁBADO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 351, 'descrip' => 'PLÁTANO DE ISLA P.C.-DOMINGO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 352, 'descrip' => 'PLÁTANO DE SEDA P.C.- MARTES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 353, 'descrip' => 'PLÁTANO DE SEDA P.C.- JUEVES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 354, 'descrip' => 'PLÁTANO DE SEDA P.C.- SÁBADO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 355, 'descrip' => 'PLÁTANO DE SEDA P.C.- MIERCOLES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 356, 'descrip' => 'PLÁTANO DE SEDA P.C.- VIERNES' , 'ingredient_type_id' => 3 ],
            [ 'id' => 357, 'descrip' => 'PLÁTANO DE SEDA P.C.- DOMINGO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 358, 'descrip' => 'YACÓN' , 'ingredient_type_id' => 3 ],
            [ 'id' => 359, 'descrip' => 'TANGELO' , 'ingredient_type_id' => 3 ],
            [ 'id' => 360, 'descrip' => 'ACEITE COMPUESTO (VEGETAL 70% PESCADO 30%)' , 'ingredient_type_id' => 4 ],
            [ 'id' => 361, 'descrip' => 'ACEITE DE PESCADO, HIDROGENADO' , 'ingredient_type_id' => 4 ],
            [ 'id' => 362, 'descrip' => 'ACEITE VEGETAL DE ALGODÓN' , 'ingredient_type_id' => 4 ],
            [ 'id' => 363, 'descrip' => 'ACEITE VEGETAL DE GIRASOL' , 'ingredient_type_id' => 4 ],
            [ 'id' => 364, 'descrip' => 'ACEITE VEGETAL DE MAÍZ' , 'ingredient_type_id' => 4 ],
            [ 'id' => 365, 'descrip' => 'ACEITE VEGETAL DE MANÍ' , 'ingredient_type_id' => 4 ],
            [ 'id' => 366, 'descrip' => 'ACEITE VEGETAL DE OLIVO' , 'ingredient_type_id' => 4 ],
            [ 'id' => 367, 'descrip' => 'ACEITE VEGETAL DE PALMA' , 'ingredient_type_id' => 4 ],
            [ 'id' => 368, 'descrip' => 'ACEITE VEGETAL DE SOYA' , 'ingredient_type_id' => 4 ],
            [ 'id' => 369, 'descrip' => 'ALMENDRAS' , 'ingredient_type_id' => 4 ],
            [ 'id' => 370, 'descrip' => 'AVELLANAS' , 'ingredient_type_id' => 4 ],
            [ 'id' => 371, 'descrip' => 'CACAO, SEMILLAS SECAS' , 'ingredient_type_id' => 4 ],
            [ 'id' => 372, 'descrip' => 'CASTAÑA PERUANA (NUEZ DE BRASIL)' , 'ingredient_type_id' => 4 ],
            [ 'id' => 373, 'descrip' => 'MANÍ CRUDO, PELADO CON PELÍCULA' , 'ingredient_type_id' => 4 ],
            [ 'id' => 374, 'descrip' => 'MANÍ SANCOCHADO' , 'ingredient_type_id' => 4 ],
            [ 'id' => 375, 'descrip' => 'MANÍ TOSTADO, SIN PELÍCULA' , 'ingredient_type_id' => 4 ],
            [ 'id' => 376, 'descrip' => 'MANTECA DE CERDO' , 'ingredient_type_id' => 4 ],
            [ 'id' => 377, 'descrip' => 'MANTECA VEGETAL' , 'ingredient_type_id' => 4 ],
            [ 'id' => 378, 'descrip' => 'MANTEQUILLA' , 'ingredient_type_id' => 4 ],
            [ 'id' => 379, 'descrip' => 'MANTEQUILLA CON SAL' , 'ingredient_type_id' => 4 ],
            [ 'id' => 380, 'descrip' => 'MARGARINA VEGETAL CON SAL' , 'ingredient_type_id' => 4 ],
            [ 'id' => 381, 'descrip' => 'NUECES' , 'ingredient_type_id' => 4 ],
            [ 'id' => 382, 'descrip' => 'ACEITE  VEGETAL, P.F' , 'ingredient_type_id' => 4 ],
            [ 'id' => 383, 'descrip' => 'ALMEJA BLANCA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 384, 'descrip' => 'BARQUILLOS P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 385, 'descrip' => 'CAMARONCITO SECO (CHINO)' , 'ingredient_type_id' => 5 ],
            [ 'id' => 386, 'descrip' => 'CAMARONES FRESCOS P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 387, 'descrip' => 'CANGREJO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 388, 'descrip' => 'CANGREJOS FRESCOS P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 389, 'descrip' => 'CARACOL P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 390, 'descrip' => 'CARACOLES P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 391, 'descrip' => 'CHANQUE, LOCO O TOLINA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 392, 'descrip' => 'CHOROS SIN CONCHA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 393, 'descrip' => 'CONCHAS DE ABANICO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 394, 'descrip' => 'ERIZO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 395, 'descrip' => 'LANGOSTINO BLANCO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 396, 'descrip' => 'LAPAS P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 397, 'descrip' => 'MACHAS' , 'ingredient_type_id' => 5 ],
            [ 'id' => 398, 'descrip' => 'PESCADO ACARABUAZÚ, SALADO DESHIDRATADO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 399, 'descrip' => 'PESCADO ANCHOVETA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 400, 'descrip' => 'PESCADO ATÚN, EN CONSERVA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 401, 'descrip' => 'PESCADO ATÚN, ENLATADO CON AGUA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 402, 'descrip' => 'PESCADO ATÚN, ENLATADO EN ACEITE ' , 'ingredient_type_id' => 5 ],
            [ 'id' => 403, 'descrip' => 'PESCADO ATÚN, FRESCO CRUDO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 404, 'descrip' => 'PESCADO AYANQUE' , 'ingredient_type_id' => 5 ],
            [ 'id' => 405, 'descrip' => 'PESCADO AYANQUE O CACHEMA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 406, 'descrip' => 'PESCADO BACALAO FRESCO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 407, 'descrip' => 'PESCADO BACALAO SECO SALADO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 408, 'descrip' => 'PESCADO BAGRE P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 409, 'descrip' => 'PESCADO BONITO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 410, 'descrip' => 'PESCADO BONITO, HUEVERA DE' , 'ingredient_type_id' => 5 ],
            [ 'id' => 411, 'descrip' => 'PESCADO BONITO, MÚSCULO CLARO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 412, 'descrip' => 'PESCADO BONITO, MÚSCULO OSCURO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 413, 'descrip' => 'PESCADO BONITO, PULPA ASADA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 414, 'descrip' => 'PESCADO BONITO, SECO SALADO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 415, 'descrip' => 'PESCADO BOQUICHICO, SALADO DESHIDRATADO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 416, 'descrip' => 'PESCADO CABALLA, EN CONSERVA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 417, 'descrip' => 'PESCADO CABALLA, FRESCO CRUDO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 418, 'descrip' => 'PESCADO CABALLA, SALADO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 419, 'descrip' => 'PESCADO CABINZA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 420, 'descrip' => 'PESCADO CABRILLA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 421, 'descrip' => 'PESCADO CARACHAMA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 422, 'descrip' => 'PESCADO CAZÓN P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 423, 'descrip' => 'PESCADO CHITA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 424, 'descrip' => 'PESCADO CHITA, HUEVERA DE' , 'ingredient_type_id' => 5 ],
            [ 'id' => 425, 'descrip' => 'PESCADO CHITA, PULPA ASADA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 426, 'descrip' => 'PESCADO COCO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 427, 'descrip' => 'PESCADO COJINOVA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 428, 'descrip' => 'PESCADO CONGRIO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 429, 'descrip' => 'PESCADO CORVINA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 430, 'descrip' => 'PESCADO FUASACO, CON ESPINAS' , 'ingredient_type_id' => 5 ],
            [ 'id' => 431, 'descrip' => 'PESCADO JUREL, EN CONSERVA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 432, 'descrip' => 'PESCADO JUREL, FRESCO CRUDO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 433, 'descrip' => 'PESCADO LENGUADO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 434, 'descrip' => 'PESCADO LISA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 435, 'descrip' => 'PESCADO LORNA, FRESCO CRUDO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 436, 'descrip' => 'PESCADO LORNA, PULPA SECA SALADA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 437, 'descrip' => 'PESCADO LORNA, SALADO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 438, 'descrip' => 'PESCADO MACHETE' , 'ingredient_type_id' => 5 ],
            [ 'id' => 439, 'descrip' => 'PESCADO MAPARATE, CON ESPINAS' , 'ingredient_type_id' => 5 ],
            [ 'id' => 440, 'descrip' => 'PESCADO MERLUZA, FRESCO CRUDO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 441, 'descrip' => 'PESCADO MERLUZA, SECO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 442, 'descrip' => 'PESCADO PAICHE, SECO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 443, 'descrip' => 'PESCADO PAMPANITO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 444, 'descrip' => 'PESCADO PAÑA, SALADO DESHIDRATADO P.C' , 'ingredient_type_id' => 5 ],
            [ 'id' => 445, 'descrip' => 'PESCADO PEJERREY' , 'ingredient_type_id' => 5 ],
            [ 'id' => 446, 'descrip' => 'PESCADO PEJESAPO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 447, 'descrip' => 'PESCADO PEJESAPO, PULPA ASADA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 448, 'descrip' => 'PESCADO PEJESAPO, PULPA SANCOCHADA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 449, 'descrip' => 'PESCADO PERICO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 450, 'descrip' => 'PESCADO PINTADILLA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 451, 'descrip' => 'PESCADO RACTACARA, CON ESPINAS' , 'ingredient_type_id' => 5 ],
            [ 'id' => 452, 'descrip' => 'PESCADO RAYA, PULPA ASADA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 453, 'descrip' => 'PESCADO RÓBALO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 454, 'descrip' => 'PESCADO SARDINA, CON ACEITE' , 'ingredient_type_id' => 5 ],
            [ 'id' => 455, 'descrip' => 'PESCADO SARDINA, CON TOMATE' , 'ingredient_type_id' => 5 ],
            [ 'id' => 456, 'descrip' => 'PESCADO SARDINA, EN GRATED (EN CONSERVA)' , 'ingredient_type_id' => 5 ],
            [ 'id' => 457, 'descrip' => 'PESCADO SARDINA, FILETE (EN CONSERVA)' , 'ingredient_type_id' => 5 ],
            [ 'id' => 458, 'descrip' => 'PESCADO SARDINA, FRESCO CRUDO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 459, 'descrip' => 'PESCADO TOYO, FRESCO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 460, 'descrip' => 'PESCADO TOYO, SECO SALADO' , 'ingredient_type_id' => 5 ],
            [ 'id' => 461, 'descrip' => 'PESCADO TRAMBOYO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 462, 'descrip' => 'PESCADO TRUCHA ROSADA P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 463, 'descrip' => 'PESCADO TRUCHA, EN CONSERVA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 464, 'descrip' => 'PESCADO TRUCHA, FRESCA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 465, 'descrip' => 'PESCADO YAHUARACHI, CON ESPINAS' , 'ingredient_type_id' => 5 ],
            [ 'id' => 466, 'descrip' => 'PESCADO YULIYA, CON ESPINAS' , 'ingredient_type_id' => 5 ],
            [ 'id' => 467, 'descrip' => 'PESCADO ZÚNGARO, SALADO DESHIDRATADO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 468, 'descrip' => 'PIQUE P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 469, 'descrip' => 'POTA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 470, 'descrip' => 'POTA, CONCENTRADO PROTEICO DE ' , 'ingredient_type_id' => 5 ],
            [ 'id' => 471, 'descrip' => 'PULPO P.C.' , 'ingredient_type_id' => 5 ],
            [ 'id' => 472, 'descrip' => 'PESCADO ANCHOVETA' , 'ingredient_type_id' => 5 ],
            [ 'id' => 473, 'descrip' => 'BALLENA, CARNE PULPA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 474, 'descrip' => 'CABEZA DE CARNERO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 475, 'descrip' => 'CARNERO, CORAZÓN DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 476, 'descrip' => 'CARNERO, HÍGADO DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 477, 'descrip' => 'CARNERO, PANZA DE (MONDONGO)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 478, 'descrip' => 'CARNERO, PATAS SANCOCHADAS DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 479, 'descrip' => 'CARNERO, PULMÓN DE (BOFE)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 480, 'descrip' => 'CARNERO, RIÑÓN' , 'ingredient_type_id' => 6 ],
            [ 'id' => 481, 'descrip' => 'CARNERO, SESOS DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 482, 'descrip' => 'CARNERO, PULPA GORDA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 483, 'descrip' => 'CARNERO, PULPA MUY MAGRA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 484, 'descrip' => 'CARNERO PULPA SEMIGORDA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 485, 'descrip' => 'CERDO, CARNE SIN HUESO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 486, 'descrip' => 'CERDO, HÍGADO DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 487, 'descrip' => 'CERDO, PATAS SEMIGORDAS' , 'ingredient_type_id' => 6 ],
            [ 'id' => 488, 'descrip' => 'CERDO, PULMÓN DE (BOFE)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 489, 'descrip' => 'CERDO, RIÑÓN DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 490, 'descrip' => 'CHIVO, CARNE PULPA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 491, 'descrip' => 'CONEJO, CARNE PULPA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 492, 'descrip' => 'GALLINA, PECHUGA DE (SIN PIEL)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 493, 'descrip' => 'GALLINA, PIERNA DE (SIN PIEL)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 494, 'descrip' => 'MAJAZ, CARNE PULPA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 495, 'descrip' => 'MOTELO, CARNE PULPA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 496, 'descrip' => 'PATO, CARNE DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 497, 'descrip' => 'PAVO, CARNE DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 498, 'descrip' => 'POLLO, CARNE PULPA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 499, 'descrip' => 'POLLO, CORAZÓN DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 500, 'descrip' => 'POLLO, HÍGADO DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 501, 'descrip' => 'POLLO, SANGRE COCIDA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 502, 'descrip' => 'POLLO, SANGRE CRUDA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 503, 'descrip' => 'RANA, CARNE DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 504, 'descrip' => 'TORTUGA CHARAPA, CARNE DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 505, 'descrip' => 'RES, BAZO DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 506, 'descrip' => 'RES, CABEZA SANCOCHADA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 507, 'descrip' => 'RES, CARNE PULPA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 508, 'descrip' => 'RES, CORAZÓN DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 509, 'descrip' => 'RES, CRIADILLAS DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 510, 'descrip' => 'RES, HÍGADO DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 511, 'descrip' => 'RES, LENGUA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 512, 'descrip' => 'RES, PANZA DE (MONDONGO)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 513, 'descrip' => 'RES, PATA SANCOCHADA DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 514, 'descrip' => 'RES, PULMÓN DE (BOFE)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 515, 'descrip' => 'RES, RIÑÓN DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 516, 'descrip' => 'RES, SESOS DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 517, 'descrip' => 'RES, UBRE DE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 518, 'descrip' => 'CARNERO, CARNE SECA SIN HUESO (CHALONA)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 519, 'descrip' => 'CHICHARRÓN DE CERDO (COCIDO)' , 'ingredient_type_id' => 6 ],
            [ 'id' => 520, 'descrip' => 'CHICHARRÓN DE PRENSA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 521, 'descrip' => 'CHORIZO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 522, 'descrip' => 'JAMÓN DEL PAÍS' , 'ingredient_type_id' => 6 ],
            [ 'id' => 523, 'descrip' => 'JAMONADA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 524, 'descrip' => 'MORTADELA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 525, 'descrip' => 'PATÉ' , 'ingredient_type_id' => 6 ],
            [ 'id' => 526, 'descrip' => 'QUESO DE CHANCHO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 527, 'descrip' => 'RELLENO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 528, 'descrip' => 'SALCHICHA BLANCA CHICA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 529, 'descrip' => 'SALCHICHA BLANCA GRANDE' , 'ingredient_type_id' => 6 ],
            [ 'id' => 530, 'descrip' => 'HOT DOG' , 'ingredient_type_id' => 6 ],
            [ 'id' => 531, 'descrip' => 'SALCHICHA DE "HUACHO"' , 'ingredient_type_id' => 6 ],
            [ 'id' => 532, 'descrip' => 'TOCINO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 533, 'descrip' => 'RES GUISO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 534, 'descrip' => 'MENUDENCIA DE POLLO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 535, 'descrip' => 'ASADO  CUADRADO' , 'ingredient_type_id' => 6 ],
            [ 'id' => 536, 'descrip' => 'POLLO - MOLLEJA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 537, 'descrip' => 'POLLO - HUESOS' , 'ingredient_type_id' => 6 ],
            [ 'id' => 538, 'descrip' => 'POLLO ENTERO S/M' , 'ingredient_type_id' => 6 ],
            [ 'id' => 539, 'descrip' => 'POLLO, PECHUGA S/M' , 'ingredient_type_id' => 6 ],
            [ 'id' => 540, 'descrip' => 'CARNE DE RES MOLIDA' , 'ingredient_type_id' => 6 ],
            [ 'id' => 541, 'descrip' => 'BOLA DE LOMO RES' , 'ingredient_type_id' => 6 ],
            [ 'id' => 542, 'descrip' => 'CHULETA DE CERDO X 170' , 'ingredient_type_id' => 6 ],
            [ 'id' => 543, 'descrip' => 'CREMA DE LECHE, ESPESA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 544, 'descrip' => 'CREMA DE LECHE, RALA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 545, 'descrip' => 'LECHE CONDENSADA NESTLÉ' , 'ingredient_type_id' => 7 ],
            [ 'id' => 546, 'descrip' => 'LECHE EN POLVO DESCREMADA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 547, 'descrip' => 'LECHE EN POLVO ENTERA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 548, 'descrip' => 'LECHE DESCREMADA lata x 400 mL' , 'ingredient_type_id' => 7 ],
            [ 'id' => 549, 'descrip' => 'LECHE EVAPORADA ENTERA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 550, 'descrip' => 'LECHE FRESCA C/MENOS DE 1% GRASA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 551, 'descrip' => 'LECHE FRESCA CAJA ENTERA PLUSA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 552, 'descrip' => 'LECHE FRESCA DE CABRA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 553, 'descrip' => 'LECHE FRESCA DE VACA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 554, 'descrip' => 'LECHE MATERNA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 555, 'descrip' => 'QUESO FRESCO DE CABRA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 556, 'descrip' => 'QUESO FRESCO DE VACA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 557, 'descrip' => 'QUESO MANTECOSO' , 'ingredient_type_id' => 7 ],
            [ 'id' => 558, 'descrip' => 'QUESO PARMESANO DURO' , 'ingredient_type_id' => 7 ],
            [ 'id' => 559, 'descrip' => 'YOGURT DE FRESA x 1 Lt' , 'ingredient_type_id' => 7 ],
            [ 'id' => 560, 'descrip' => 'YOGURT FRUTADO DE LECHE SEMIDESCREMADA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 561, 'descrip' => 'YOGURT FRUTADO LECHE DESCREMADA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 562, 'descrip' => 'YOGURT NATURAL LECHE DESCREMADA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 563, 'descrip' => 'LECHE CHOCOLATADA  x 180 mL' , 'ingredient_type_id' => 7 ],
            [ 'id' => 564, 'descrip' => 'LECHE BOLSITARRO LAIVE TRADICIONAL x 400 mL' , 'ingredient_type_id' => 7 ],
            [ 'id' => 565, 'descrip' => 'LECHE EVAPORADA DHA ' , 'ingredient_type_id' => 7 ],
            [ 'id' => 566, 'descrip' => 'LECHE EVAPORADA NAM 2' , 'ingredient_type_id' => 7 ],
            [ 'id' => 567, 'descrip' => 'LECHE GLORIA SUPER LIGHT  ' , 'ingredient_type_id' => 7 ],
            [ 'id' => 568, 'descrip' => 'LECHE DESLACTOSADA' , 'ingredient_type_id' => 7 ],
            [ 'id' => 569, 'descrip' => 'LECHE GLORIA ROJA LIGHT' , 'ingredient_type_id' => 7 ],
            [ 'id' => 570, 'descrip' => 'LECHE IDEAL AMANECER x 400 mL' , 'ingredient_type_id' => 7 ],
            [ 'id' => 571, 'descrip' => 'LECHE EVAPORADA "PURA VIDA"' , 'ingredient_type_id' => 7 ],
            [ 'id' => 572, 'descrip' => 'LECHE LAIVE LIGHT (tetrapack x 500 mL)' , 'ingredient_type_id' => 7 ],
            [ 'id' => 573, 'descrip' => 'YOGURT BATIMIX CHOCOLATE' , 'ingredient_type_id' => 7 ],
            [ 'id' => 574, 'descrip' => 'YOGURT BATIMIX CORN FLAKES' , 'ingredient_type_id' => 7 ],
            [ 'id' => 575, 'descrip' => 'YOGURT DURAZNO x 1LT' , 'ingredient_type_id' => 7 ],
            [ 'id' => 576, 'descrip' => 'YOGURT VAINILLA x 1 LT' , 'ingredient_type_id' => 7 ],
            [ 'id' => 577, 'descrip' => 'YOGURT LAIVE BOTELLA x 180 mL' , 'ingredient_type_id' => 7 ],
            [ 'id' => 578, 'descrip' => 'YOGURT SBELL x 1 LT' , 'ingredient_type_id' => 7 ],
            [ 'id' => 579, 'descrip' => 'CERVEZA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 580, 'descrip' => 'CHICHA DE AGUAJE' , 'ingredient_type_id' => 8 ],
            [ 'id' => 581, 'descrip' => 'CHICHA DE CEBADA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 582, 'descrip' => 'CHICHA DE JORA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 583, 'descrip' => 'CHICHA DE MAIZ MORADO CON AZÚCAR' , 'ingredient_type_id' => 8 ],
            [ 'id' => 584, 'descrip' => 'CHICHA DE MANÍ' , 'ingredient_type_id' => 8 ],
            [ 'id' => 585, 'descrip' => 'CHICHA DE PIJUAYO' , 'ingredient_type_id' => 8 ],
            [ 'id' => 586, 'descrip' => 'CHICHA DE SOYA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 587, 'descrip' => 'CHICHA DE YUCA (MASATO)' , 'ingredient_type_id' => 8 ],
            [ 'id' => 588, 'descrip' => 'COCA COLA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 589, 'descrip' => 'INCA KOLA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 590, 'descrip' => 'LECHE DE SOYA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 591, 'descrip' => 'TÉ Y CANELA' , 'ingredient_type_id' => 8 ],
            [ 'id' => 592, 'descrip' => 'VINO BLANCO (GRADO ALCOHOLICO: 12.0)' , 'ingredient_type_id' => 8 ],
            [ 'id' => 593, 'descrip' => 'VINO TINTO  (GRADO ALCOHOLICO: 10.2)' , 'ingredient_type_id' => 8 ],
            [ 'id' => 594, 'descrip' => 'CRUSH NARANJA  x 1LT' , 'ingredient_type_id' => 8 ],
            [ 'id' => 595, 'descrip' => 'SPRITE CERO x 1.75 LT' , 'ingredient_type_id' => 8 ],
            [ 'id' => 596, 'descrip' => 'TAMPICO x 1 LT' , 'ingredient_type_id' => 8 ],
            [ 'id' => 597, 'descrip' => 'HUEVO DE CHARAPA P.C.' , 'ingredient_type_id' => 9 ],
            [ 'id' => 598, 'descrip' => 'HUEVO DE GALLINA, CLARA DE' , 'ingredient_type_id' => 9 ],
            [ 'id' => 599, 'descrip' => 'HUEVO DE GALLINA, DURO' , 'ingredient_type_id' => 9 ],
            [ 'id' => 600, 'descrip' => 'HUEVO DE GALLINA P.C.' , 'ingredient_type_id' => 9 ],
            [ 'id' => 601, 'descrip' => 'HUEVO DE GALLINA, YEMA DE' , 'ingredient_type_id' => 9 ],
            [ 'id' => 602, 'descrip' => 'HUEVO DE TORTUGA MOTELO P.C.' , 'ingredient_type_id' => 9 ],
            [ 'id' => 603, 'descrip' => 'HUEVO DE PATA P.C.' , 'ingredient_type_id' => 9 ],
            [ 'id' => 604, 'descrip' => 'HUEVO DE PATA, YEMA DE' , 'ingredient_type_id' => 9 ],
            [ 'id' => 605, 'descrip' => 'HUEVO DE TORTUGA TARICAYA P.C.' , 'ingredient_type_id' => 9 ],
            [ 'id' => 606, 'descrip' => 'AZÚCAR GRANULADA O REFINADA' , 'ingredient_type_id' => 10 ],
            [ 'id' => 607, 'descrip' => 'AZÚCAR RUBIA' , 'ingredient_type_id' => 10 ],
            [ 'id' => 608, 'descrip' => 'CHANCACA' , 'ingredient_type_id' => 10 ],
            [ 'id' => 609, 'descrip' => 'MIEL DE ABEJA' , 'ingredient_type_id' => 10 ],
            [ 'id' => 610, 'descrip' => 'MIEL DE CAÑA' , 'ingredient_type_id' => 10 ],
            [ 'id' => 611, 'descrip' => 'MERMELADA DE DURAZNO' , 'ingredient_type_id' => 10 ],
            [ 'id' => 612, 'descrip' => 'MERMELADA FRUTILLA' , 'ingredient_type_id' => 10 ],
            [ 'id' => 613, 'descrip' => 'ALGAROBINA MN' , 'ingredient_type_id' => 10 ],
            [ 'id' => 614, 'descrip' => 'ACHIOTE SECO' , 'ingredient_type_id' => 11 ],
            [ 'id' => 615, 'descrip' => 'ALGAS' , 'ingredient_type_id' => 11 ],
            [ 'id' => 616, 'descrip' => 'AZAFRÁN (PALILLO FRESCO)' , 'ingredient_type_id' => 11 ],
            [ 'id' => 617, 'descrip' => 'CAFÉ GRANO SIN TOSTAR' , 'ingredient_type_id' => 11 ],
            [ 'id' => 618, 'descrip' => 'CAFÉ SIN AZÚCAR' , 'ingredient_type_id' => 11 ],
            [ 'id' => 619, 'descrip' => 'CALDO DE AVE, TABLETAS' , 'ingredient_type_id' => 11 ],
            [ 'id' => 620, 'descrip' => 'CALDO DE CARNE, TABLETAS' , 'ingredient_type_id' => 11 ],
            [ 'id' => 621, 'descrip' => 'CHOCOLATE SIMPLE CON AZÚCAR' , 'ingredient_type_id' => 11 ],
            [ 'id' => 622, 'descrip' => 'COCHAYUYO' , 'ingredient_type_id' => 11 ],
            [ 'id' => 623, 'descrip' => 'COCOA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 624, 'descrip' => 'COMINOS' , 'ingredient_type_id' => 11 ],
            [ 'id' => 625, 'descrip' => 'EXTRACTO DE ALGARROBO EN POLVO' , 'ingredient_type_id' => 11 ],
            [ 'id' => 626, 'descrip' => 'HONGOS (CALLAMPA)' , 'ingredient_type_id' => 11 ],
            [ 'id' => 627, 'descrip' => 'LAUREL' , 'ingredient_type_id' => 11 ],
            [ 'id' => 628, 'descrip' => 'PIMIENTA NEGRA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 629, 'descrip' => 'TE HOJAS SECAS' , 'ingredient_type_id' => 11 ],
            [ 'id' => 630, 'descrip' => 'VINAGRE' , 'ingredient_type_id' => 11 ],
            [ 'id' => 631, 'descrip' => 'YUYO FRESCO P.C.' , 'ingredient_type_id' => 11 ],
            [ 'id' => 632, 'descrip' => 'nutrihem1' , 'ingredient_type_id' => 11 ],
            [ 'id' => 633, 'descrip' => 'Micronutriente' , 'ingredient_type_id' => 11 ],
            [ 'id' => 634, 'descrip' => 'Miel' , 'ingredient_type_id' => 11 ],
            [ 'id' => 635, 'descrip' => 'CANELA CHINA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 636, 'descrip' => 'CLAVO DE OLOR' , 'ingredient_type_id' => 11 ],
            [ 'id' => 637, 'descrip' => 'SAL YODADA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 638, 'descrip' => 'SILLAO ( SALSA DE SOYA)' , 'ingredient_type_id' => 11 ],
            [ 'id' => 639, 'descrip' => 'KIÓN' , 'ingredient_type_id' => 11 ],
            [ 'id' => 640, 'descrip' => 'AJINOMOTO' , 'ingredient_type_id' => 11 ],
            [ 'id' => 641, 'descrip' => 'CARNICO  SIN HUESO' , 'ingredient_type_id' => 11 ],
            [ 'id' => 642, 'descrip' => 'KETCHUP' , 'ingredient_type_id' => 11 ],
            [ 'id' => 643, 'descrip' => 'CHICHA DE JORA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 644, 'descrip' => 'CHAMPIÑONES' , 'ingredient_type_id' => 11 ],
            [ 'id' => 645, 'descrip' => 'MOSTAZA ' , 'ingredient_type_id' => 11 ],
            [ 'id' => 646, 'descrip' => 'KETCHUP x 250 sachets' , 'ingredient_type_id' => 11 ],
            [ 'id' => 647, 'descrip' => 'MAYONESA x 250 sachets' , 'ingredient_type_id' => 11 ],
            [ 'id' => 648, 'descrip' => 'AJI x 250 sachets' , 'ingredient_type_id' => 11 ],
            [ 'id' => 649, 'descrip' => 'MOSTAZA x 250 sachets' , 'ingredient_type_id' => 11 ],
            [ 'id' => 650, 'descrip' => 'GELATINA DE FRESA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 651, 'descrip' => 'PANETÓN' , 'ingredient_type_id' => 11 ],
            [ 'id' => 652, 'descrip' => 'PUDIN DE VAINILLA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 653, 'descrip' => 'PUDIN DE CHOCOLATE' , 'ingredient_type_id' => 11 ],
            [ 'id' => 654, 'descrip' => 'CEDRON' , 'ingredient_type_id' => 11 ],
            [ 'id' => 655, 'descrip' => 'FLAN DE VAINILLA' , 'ingredient_type_id' => 11 ],
            [ 'id' => 656, 'descrip' => 'COLAPIZ' , 'ingredient_type_id' => 11 ],
            [ 'id' => 657, 'descrip' => 'PASTA DE TOMATE' , 'ingredient_type_id' => 11 ],
            [ 'id' => 658, 'descrip' => 'MENSI' , 'ingredient_type_id' => 11 ],
            [ 'id' => 659, 'descrip' => 'SALSA OSTION' , 'ingredient_type_id' => 11 ],
            [ 'id' => 660, 'descrip' => 'MOLDE DE KEKE MARMOLEADO' , 'ingredient_type_id' => 11 ],
            [ 'id' => 661, 'descrip' => 'MANJAR BLANCO' , 'ingredient_type_id' => 11 ],
            [ 'id' => 662, 'descrip' => 'ACHIRA BLANCA (RIZOMA, RAÍZ)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 663, 'descrip' => 'ACHIRA MORADA (RIZOMA, RAÍZ)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 664, 'descrip' => 'ALPACA, CARNE PULPA DE' , 'ingredient_type_id' => 12 ],
            [ 'id' => 665, 'descrip' => 'ASKA, AL ESTADO NATURAL (CRUSTACEO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 666, 'descrip' => 'ASKA, SOMETIDO A COCCIÓN (CRUSTACEO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 667, 'descrip' => 'CAMOTE DE HUARAYOC' , 'ingredient_type_id' => 12 ],
            [ 'id' => 668, 'descrip' => 'CAMOTE DESHIDRATADO' , 'ingredient_type_id' => 12 ],
            [ 'id' => 669, 'descrip' => 'CAMOTE DESHIDRATADO TRATADO CON LEJIA' , 'ingredient_type_id' => 12 ],
            [ 'id' => 670, 'descrip' => 'CARAMBOLA (FRUTA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 671, 'descrip' => 'CAYA OCAS (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 672, 'descrip' => 'CAZA O PARKA (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 673, 'descrip' => 'CHIJCHIPA P.C. (HORTALIZA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 674, 'descrip' => 'CHULLCOS, AJOS SILVESTRES (HORTALIZA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 675, 'descrip' => 'CUSHURO O NOSTOC DESHIDRATADA (ALGA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 676, 'descrip' => 'CUSHUSHO (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 677, 'descrip' => 'CUY, CARNE DE' , 'ingredient_type_id' => 12 ],
            [ 'id' => 678, 'descrip' => 'DALE - DALE (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 679, 'descrip' => 'FRIJOL DE IBERIA (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 680, 'descrip' => 'GIGANTE ROJO, CÁSCARA DEL GRANO (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 681, 'descrip' => 'GIGANTE ROJO, CÁSCARA FRESCA DEL GRANO (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 682, 'descrip' => 'GIGANTE ROJO, PULPA FRESCA (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 683, 'descrip' => 'GIGANTE ROJO, PULPA SECA (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 684, 'descrip' => 'HEMICO LEGUMINOSO (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 685, 'descrip' => 'HIWICTO MARFIL OSCURO (CEREAL)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 686, 'descrip' => 'HIWICTO NEGRO (CEREAL)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 687, 'descrip' => 'IGUANA PAPA (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 688, 'descrip' => 'KARA CENIZA O KALA (CEREAL)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 689, 'descrip' => 'KARA COLOR PAJIZO (CEREAL)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 690, 'descrip' => 'LLAMA, CARNE SECA DE (CHARQUI)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 691, 'descrip' => 'LLAMPUN CJANA "CJANA-CJANA" (HORTALIZA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 692, 'descrip' => 'LLIPTA SARA (VARIEDAD DE MAÍZ)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 693, 'descrip' => 'NOPU - ZUMACA (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 694, 'descrip' => 'OCA DESHIDRATADA (CCAYA) P.C.' , 'ingredient_type_id' => 12 ],
            [ 'id' => 695, 'descrip' => 'OCA P.C.' , 'ingredient_type_id' => 12 ],
            [ 'id' => 696, 'descrip' => 'PALLAR DEL RIO MANÚ (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 697, 'descrip' => 'POROTO DE CUMBASA (LEGUMINOSA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 698, 'descrip' => 'QUILLU UNCUCHA (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 699, 'descrip' => 'SACHAPAPA BLANCA, BULBO' , 'ingredient_type_id' => 12 ],
            [ 'id' => 700, 'descrip' => 'SACHAPAPA, BULBO AEREO' , 'ingredient_type_id' => 12 ],
            [ 'id' => 701, 'descrip' => 'SAJINO, CARNE PULPA DE' , 'ingredient_type_id' => 12 ],
            [ 'id' => 702, 'descrip' => 'TALLAPAQUI CULLI (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 703, 'descrip' => 'TALLAPAQUI YURAK (TUBÉRCULO)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 704, 'descrip' => 'TOMATE DE PALITO (HORTALIZA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 705, 'descrip' => 'VENADO, CARNE PULPA DE' , 'ingredient_type_id' => 12 ],
            [ 'id' => 706, 'descrip' => 'VENADO, CARNE SECA DE' , 'ingredient_type_id' => 12 ],
            [ 'id' => 707, 'descrip' => 'WARRA P.C. (FRUTA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 708, 'descrip' => 'YAKU P.C. (FRUTA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 709, 'descrip' => 'YUCA DE MOJA' , 'ingredient_type_id' => 12 ],
            [ 'id' => 710, 'descrip' => 'ZAPALLITO (HORTALIZA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 711, 'descrip' => 'ZAPALLO AVINCA (HORTALIZA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 712, 'descrip' => 'ZAPALLO OMBLIGO (HORTALIZA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 713, 'descrip' => 'ZIQUI - ZAPA (HORMIGA)' , 'ingredient_type_id' => 12 ],
            [ 'id' => 714, 'descrip' => 'MAYONESA ' , 'ingredient_type_id' => 12 ],
            [ 'id' => 715, 'descrip' => 'SOJA' , 'ingredient_type_id' => 12 ],
            [ 'id' => 716, 'descrip' => 'AL 110 MATERNIZADA' , 'ingredient_type_id' => 13 ],
            [ 'id' => 717, 'descrip' => 'CERELAC MANZANA' , 'ingredient_type_id' => 13 ],
            [ 'id' => 718, 'descrip' => 'CERELAC TRIGO' , 'ingredient_type_id' => 13 ],
            [ 'id' => 719, 'descrip' => 'ELEDON MATERNIZADA' , 'ingredient_type_id' => 13 ],
            [ 'id' => 720, 'descrip' => 'NAN MATERNIZADA' , 'ingredient_type_id' => 13 ],
            [ 'id' => 721, 'descrip' => 'NESTÚM CEREAL MIXTO' , 'ingredient_type_id' => 13 ],
            [ 'id' => 722, 'descrip' => 'NESTUM TRES CEREALES' , 'ingredient_type_id' => 13 ],
            [ 'id' => 723, 'descrip' => 'PELARGÓN MATERNIZADA' , 'ingredient_type_id' => 13 ],
            [ 'id' => 724, 'descrip' => 'ARRACACHA O RACACHA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 725, 'descrip' => 'ASHIPA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 726, 'descrip' => 'CAMOTE AMARILLO P.C.' , 'ingredient_type_id' => 14 ],
            [ 'id' => 727, 'descrip' => 'CAMOTE BLANCO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 728, 'descrip' => 'CAMOTE MORADO SIN CÁSCARA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 729, 'descrip' => 'CAMOTE, HARINA DE' , 'ingredient_type_id' => 14 ],
            [ 'id' => 730, 'descrip' => 'CURAO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 731, 'descrip' => 'KOSHÑIPA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 732, 'descrip' => 'KUROS' , 'ingredient_type_id' => 14 ],
            [ 'id' => 733, 'descrip' => 'LLACÓN' , 'ingredient_type_id' => 14 ],
            [ 'id' => 734, 'descrip' => 'MACA (TUBÉRCULO SECO)' , 'ingredient_type_id' => 14 ],
            [ 'id' => 735, 'descrip' => 'MACA SILVESTRE' , 'ingredient_type_id' => 14 ],
            [ 'id' => 736, 'descrip' => 'MACA, AFRECHILLO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 737, 'descrip' => 'HARINA DE MACA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 738, 'descrip' => 'MACA, PASTA INTEGRAL' , 'ingredient_type_id' => 14 ],
            [ 'id' => 739, 'descrip' => 'MASHUA P.C.' , 'ingredient_type_id' => 14 ],
            [ 'id' => 740, 'descrip' => 'OLLUCO SIN CÁSCARA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 741, 'descrip' => 'PAPA AMARILLA PERUANITA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 742, 'descrip' => 'PAPA BLANCA CANCHAN PARA SANCOCHAR' , 'ingredient_type_id' => 14 ],
            [ 'id' => 743, 'descrip' => 'PAPA CHUÑO NEGRO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 744, 'descrip' => 'PAPA COLOR MORADO DESHIDRATADA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 745, 'descrip' => 'PAPA HELADA AMARGA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 746, 'descrip' => 'PAPA HUAYRO CON CÁSCARA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 747, 'descrip' => 'PAPA MORAYA CHUÑO PELADO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 748, 'descrip' => 'PAPA SECA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 749, 'descrip' => 'PAPA, HARINA DE' , 'ingredient_type_id' => 14 ],
            [ 'id' => 750, 'descrip' => 'PAPAS DESHIDRATADAS CON LEJIA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 751, 'descrip' => 'PITUCA O TARO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 752, 'descrip' => 'PITUCA, HARINA DE' , 'ingredient_type_id' => 14 ],
            [ 'id' => 753, 'descrip' => 'RADICHE' , 'ingredient_type_id' => 14 ],
            [ 'id' => 754, 'descrip' => 'REMOLACHA RAÍZ' , 'ingredient_type_id' => 14 ],
            [ 'id' => 755, 'descrip' => 'SACHAPAPA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 756, 'descrip' => 'SACHAPAPA, TUBÉRCULO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 757, 'descrip' => 'YUCA AMARILLA FRESCA SIN CÁSCARA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 758, 'descrip' => 'YUCA ASADA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 759, 'descrip' => 'YUCA BLANCA FRESCA SIN CÁSCARA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 760, 'descrip' => 'YUCA BLANCA SANCOCHADA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 761, 'descrip' => 'YUCA, HARINA DE' , 'ingredient_type_id' => 14 ],
            [ 'id' => 762, 'descrip' => 'PALLAR SECO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 763, 'descrip' => 'ARVERJA PARTIDA' , 'ingredient_type_id' => 14 ],
            [ 'id' => 764, 'descrip' => 'FREJOL CANARIO' , 'ingredient_type_id' => 14 ],
            [ 'id' => 765, 'descrip' => 'GARBANZOS' , 'ingredient_type_id' => 14 ],
            [ 'id' => 766, 'descrip' => 'LENTEJAS BEBÉ' , 'ingredient_type_id' => 14 ],
            [ 'id' => 767, 'descrip' => '¨LECHE¨ DE SOYA  ¨SOY VIDA¨ x 400 mL' , 'ingredient_type_id' => 14 ],
            [ 'id' => 768, 'descrip' => 'ARRACACHA O RACACHA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 769, 'descrip' => 'ASHIPA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 770, 'descrip' => 'CAMOTE AMARILLO SIN CÁSCARA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 771, 'descrip' => 'CAMOTE BLANCO' , 'ingredient_type_id' => 15 ],
            [ 'id' => 772, 'descrip' => 'CAMOTE MORADO SIN CÁSCARA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 773, 'descrip' => 'CAMOTE, HARINA DE' , 'ingredient_type_id' => 15 ],
            [ 'id' => 774, 'descrip' => 'CURAO' , 'ingredient_type_id' => 15 ],
            [ 'id' => 775, 'descrip' => 'KOSHÑIPA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 776, 'descrip' => 'KUROS' , 'ingredient_type_id' => 15 ],
            [ 'id' => 777, 'descrip' => 'LLACÓN' , 'ingredient_type_id' => 15 ],
            [ 'id' => 778, 'descrip' => 'MACA (TUBÉRCULO SECO)' , 'ingredient_type_id' => 15 ],
            [ 'id' => 779, 'descrip' => 'MACA SILVESTRE' , 'ingredient_type_id' => 15 ],
            [ 'id' => 780, 'descrip' => 'MACA, AFRECHILLO' , 'ingredient_type_id' => 15 ],
            [ 'id' => 781, 'descrip' => 'MACA, ALMIDÓN' , 'ingredient_type_id' => 15 ],
            [ 'id' => 782, 'descrip' => 'MACA, PASTA INTEGRAL' , 'ingredient_type_id' => 15 ],
            [ 'id' => 783, 'descrip' => 'MASHUA P.C.' , 'ingredient_type_id' => 15 ],
            [ 'id' => 784, 'descrip' => 'PAPA AMARILLA ' , 'ingredient_type_id' => 15 ],
            [ 'id' => 785, 'descrip' => 'PAPA BLANCA PARA FREIR YUNGAY' , 'ingredient_type_id' => 15 ],
            [ 'id' => 786, 'descrip' => 'PAPA CHUÑO NEGRO' , 'ingredient_type_id' => 15 ],
            [ 'id' => 787, 'descrip' => 'PAPA COLOR MORADO DESHIDRATADA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 788, 'descrip' => 'PAPA HELADA AMARGA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 789, 'descrip' => 'PAPA HUAYRO CON CÁSCARA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 790, 'descrip' => 'PAPA MORAYA CHUÑO PELADO' , 'ingredient_type_id' => 15 ],
            [ 'id' => 791, 'descrip' => 'PAPA SECA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 792, 'descrip' => 'PAPA, HARINA DE' , 'ingredient_type_id' => 15 ],
            [ 'id' => 793, 'descrip' => 'PAPAS DESHIDRATADAS CON LEJIA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 794, 'descrip' => 'PITUCA O TARO' , 'ingredient_type_id' => 15 ],
            [ 'id' => 795, 'descrip' => 'PITUCA, HARINA DE' , 'ingredient_type_id' => 15 ],
            [ 'id' => 796, 'descrip' => 'RADICHE' , 'ingredient_type_id' => 15 ],
            [ 'id' => 797, 'descrip' => 'BETARRAGA P.C.' , 'ingredient_type_id' => 15 ],
            [ 'id' => 798, 'descrip' => 'SACHAPAPA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 799, 'descrip' => 'SACHAPAPA, TUBÉRCULO' , 'ingredient_type_id' => 15 ],
            [ 'id' => 800, 'descrip' => 'YUCA AMARILLA FRESCA SIN CÁSCARA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 801, 'descrip' => 'YUCA ASADA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 802, 'descrip' => 'YUCA BLANCA FRESCA SIN CÁSCARA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 803, 'descrip' => 'YUCA BLANCA SANCOCHADA' , 'ingredient_type_id' => 15 ],
            [ 'id' => 804, 'descrip' => 'YUCA, HARINA DE' , 'ingredient_type_id' => 15 ],
            [ 'id' => 805, 'descrip' => 'OCA VARIEDAD NATIVA CAYA OGA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 806, 'descrip' => 'OCA VARIEDAD NATIVA GARWUARICRA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 807, 'descrip' => 'PAPA VARIEDAD NATIVA CAPULÍ CON CÁSCARA ' , 'ingredient_type_id' => 16 ],
            [ 'id' => 808, 'descrip' => 'PAPA VARIEDAD NATIVA CARAMARQUINA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 809, 'descrip' => 'PAPA VARIEDAD NATIVA CHIMBINA AMARILLA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 810, 'descrip' => 'PAPA VARIEDAD NATIVA HUAGALINA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 811, 'descrip' => 'PAPA VARIEDAD NATIVA HUALASH CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 812, 'descrip' => 'PAPA VARIEDAD NATIVA HUAYRO CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 813, 'descrip' => 'PAPA VARIEDAD NATIVA HUEVO DE TORO CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 814, 'descrip' => 'PAPA VARIEDAD NATIVA LIMEÑA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 815, 'descrip' => 'PAPA VARIEDAD NATIVA MAGA BLANCA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 816, 'descrip' => 'PAPA VARIEDAD NATIVA PERUANITA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 817, 'descrip' => 'PAPA VARIEDAD NATIVA PUCA PAMPAMACHAY CON CÁSCARA ' , 'ingredient_type_id' => 16 ],
            [ 'id' => 818, 'descrip' => 'PAPA VARIEDAD NATIVA PUCA PISHGOSH CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 819, 'descrip' => 'PAPA VARIEDAD NATIVA QUINUAPA TULUM CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 820, 'descrip' => 'PAPA VARIEDAD NATIVA SAPA NEGRA CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 821, 'descrip' => 'PAPA VARIEDAD NATIVA YANA SHAQUE CON CÁSCARA' , 'ingredient_type_id' => 16 ],
            [ 'id' => 822, 'descrip' => 'ENSOY LATA x 1 KG' , 'ingredient_type_id' => 17 ],
            [ 'id' => 823, 'descrip' => 'PAPA BLANCA DE PUERTO MALDONADO' , 'ingredient_type_id' => 1018 ],
            [ 'id' => 824, 'descrip' => 'MANZANA RIESGO CONTAMINACION' , 'ingredient_type_id' => 1019 ],
            
        ];
    }

}
